# Secrets that want to be shell environment variables.
#
# Owns the `age.secrets` blocks for those tokens, the postActivation writer
# that materialises them into ~/.config/nix-secrets.env, and the zsh line
# that sources it. Depends on agenix.nix for the module + identity.
#
# Adding another env var = three edits here (an `age.secrets.<name>` block
# and a `write <VAR> /run/agenix/<name>` line) plus an entry in
# ../secrets/secrets.nix and the encrypted file itself.
#
# Consumed from flake.nix as:
#     (import ./extra/envvars.nix { inherit username; })
{ username }:

{ ... }: {
  age.secrets.npm-font-awesome-token = {
    file = ../secrets/npm-font-awesome-token.age;
    owner = username;
    mode = "0400";
  };
  age.secrets.npm-github-packages-token = {
    file = ../secrets/npm-github-packages-token.age;
    owner = username;
    mode = "0400";
  };

  # After agenix decrypts to /run/agenix/*, materialise the secrets we want
  # in the shell as a plain env file at ~/.config/nix-secrets.env (sourced
  # from zsh, below). `postActivation` runs at the tail of
  # `darwin-rebuild switch`, i.e. after agenix.
  #
  # `.text` is types.lines, so other modules append to this same script
  # without conflicting — extra/mailmate.nix does exactly that.
  system.activationScripts.postActivation.text = ''
    envfile="/Users/${username}/.config/nix-secrets.env"
    install -d -m 700 -o ${username} -g staff "$(dirname "$envfile")"
    tmp="$(mktemp)"
    {
      echo "# Generated by nix-darwin; rewritten on every ns."
      echo "# Do not edit; change secrets/ + extra/envvars.nix instead."
      write() {
        # %q is bash's shell-safe quoting — handles any byte in the token.
        printf 'export %s=%q\n' "$1" "$(cat "$2")"
      }
      write NPM_FONT_AWESOME_TOKEN    /run/agenix/npm-font-awesome-token
      write NPM_GITHUB_PACKAGES_TOKEN /run/agenix/npm-github-packages-token
    } > "$tmp"
    install -m 600 -o ${username} -g staff "$tmp" "$envfile"
    rm -f "$tmp"
  '';

  home-manager.users.${username} = { ... }: {
    programs.zsh.initContent = ''
      [ -r "$HOME/.config/nix-secrets.env" ] && . "$HOME/.config/nix-secrets.env"
    '';
  };
}
