# Everything that makes agenix-based secrets work on this machine:
#   - the agenix darwin module + `agenix` CLI on PATH
#   - the age identity path
#   - each encrypted-secret declaration (add new ones here)
#   - the postActivation script that materialises the plaintext env file
#   - HM bits: the zsh `source` line and `nix-restore-age-key` helper
#
# Consumed from flake.nix as:
#     (import ./extra/secrets.nix { inherit agenix username; })
#
# See README → "Secrets management (agenix)" for the operator flow
# (generating the age key, encrypting a new secret, fresh-machine bootstrap).
{ agenix, username }:

{ pkgs, ... }: {
  imports = [ agenix.darwinModules.default ];

  environment.systemPackages = [ agenix.packages.${pkgs.stdenv.hostPlatform.system}.default ];

  # Decryption uses the age key at the path below (generate with
  # `age-keygen -o ~/.config/age/keys.txt`, no passphrase). Recipients
  # live in ../secrets/secrets.nix. To add a new secret:
  #   1. add it to ../secrets/secrets.nix
  #   2. add an `age.secrets.<name>` block here
  #   3. `cd secrets && agenix -e <name>.age` (then `git add`)
  #   4. if you want it as a shell env var, add a `write` line in the
  #      activation script below.
  age.identityPaths = [ "/Users/${username}/.config/age/keys.txt" ];
  age.secrets.npm-font-awesome-token = {
    file = ../secrets/npm-font-awesome-token.age;
    owner = username;
    mode = "0400";
  };
  age.secrets.npm-github-packages-token = {
    file = ../secrets/npm-github-packages-token.age;
    owner = username;
    mode = "0400";
  };

  # After agenix decrypts to /run/agenix/*, materialise the secrets we
  # want in the shell as a plain env file at ~/.config/nix-secrets.env
  # (sourced from zsh, below). `postActivation` runs at the tail of
  # `darwin-rebuild switch`, i.e. after agenix.
  system.activationScripts.postActivation.text = ''
    envfile="/Users/${username}/.config/nix-secrets.env"
    install -d -m 700 -o ${username} -g staff "$(dirname "$envfile")"
    tmp="$(mktemp)"
    {
      echo "# Generated by nix-darwin; rewritten on every ns."
      echo "# Do not edit; change secrets/ + extra/secrets.nix instead."
      write() {
        # %q is bash's shell-safe quoting — handles any byte in the token.
        printf 'export %s=%q\n' "$1" "$(cat "$2")"
      }
      write NPM_FONT_AWESOME_TOKEN    /run/agenix/npm-font-awesome-token
      write NPM_GITHUB_PACKAGES_TOKEN /run/agenix/npm-github-packages-token
    } > "$tmp"
    install -m 600 -o ${username} -g staff "$tmp" "$envfile"
    rm -f "$tmp"
  '';

  # Home-manager side: source the generated env file, and ship a helper
  # for fresh-machine bootstrap. Merged into the user's HM config by HM's
  # module system.
  home-manager.users.${username} = { pkgs, ... }: {
    programs.zsh.initContent = ''
      [ -r "$HOME/.config/nix-secrets.env" ] && . "$HOME/.config/nix-secrets.env"
    '';

    home.packages = [
      # Fetches the age identity from 1Password on a fresh machine.
      # Refuses to overwrite an existing key. Upload command (run once,
      # after key generation) is in the README.
      (pkgs.writeShellScriptBin "nix-restore-age-key" ''
        set -euo pipefail
        key="$HOME/.config/age/keys.txt"
        if [ -e "$key" ]; then
          echo "Refusing to overwrite existing $key — move it aside first." >&2
          exit 1
        fi
        mkdir -p "$(dirname "$key")"
        op document get "nix-darwin age key" --vault Private --out-file "$key"
        chmod 600 "$key"
        echo "Restored age key to $key"
      '')
    ];
  };
}
